<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RemoteConfig.Core</AssemblyName>
    <RootNamespace>RemoteConfig.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

</Project>
